openapi: 3.0.3
info:
  title: API Server
  version: 0.0.1
servers:
  - url: https://boolean-api-server.fly.io
tags:
  - name: todo
    description: A todo list api
paths:
  /{username}/todo:
    post:
      tags:
        - todo
      summary: Add a new todo to the list
      description: Add a new todo to the list
      operationId: addTodo
      parameters:
        - name: username
          in: path
          description: your github username
          required: true
          schema:
            type: string      
      requestBody:
        description: Create a new todo in the list
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Todo'
          application/xml:
            schema:
              $ref: '#/components/schemas/Todo'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Todo'
        required: true
      responses:
        '201':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Todo'
            application/xml:
              schema:
                $ref: '#/components/schemas/Todo'
        '400':
          description: bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequest'
        '401':
          description: The username provided is not part of the boolean-uk github organisation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GithubAuthIssue'
    get:
      tags:
        - todo
      summary: Get all of the todos in the list
      description: Returns an array of all of the existing todo items in the list
      operationId: getAllTodos
      parameters:
        - name: username
          in: path
          description: your github username
          required: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Todo'
        '401':
          description: The username provided is not part of the boolean-uk github organisation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GithubAuthIssue'
  /{username}/todo/{todoId}:
    get:
      tags:
        - todo
      summary: Find todo by ID
      description: Returns a single todo
      operationId: getTodoById
      parameters:
        - name: username
          in: path
          description: your github username
          required: true
          schema:
            type: string
        - name: todoId
          in: path
          description: ID of todo to return
          required: true
          schema:
            type: number
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Todo'
        '400':
          description: id must be a number
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequest' 
        '404':
          description: Todo not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TodoNotFound'          
        '401':
          description: The username provided is not part of the boolean-uk github organisation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GithubAuthIssue'
    put:
      tags:
        - todo
      summary: Update an existing todo
      description: Update an existing todo by Id
      operationId: updateTodo
      parameters:
        - name: username
          in: path
          description: your github username
          required: true
          schema:
            type: string
        - name: todoId
          in: path
          description: ID of todo to return
          required: true
          schema:
            type: number            
      requestBody:
        description: Update an existent todo in the list
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Todo'
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Todo'
        '404':
          description: Todo not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TodoNotFound'
        '400':
          description: validation exception
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequest' 
        '401':
          description: The username provided is not part of the boolean-uk github organisation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GithubAuthIssue'
    delete:
      tags:
        - todo
      summary: Deletes a todo
      description: delete a todo
      operationId: deleteTodo
      parameters:
        - name: username
          in: path
          description: your github username
          required: true
          schema:
            type: string      
        - name: todoId
          in: path
          description: Todo id to delete
          required: true
          schema:
            type: number
      responses:
        '200':
          description: Successful deletion
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Todo'
        '400':
          description: id must be a number
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequest'            
        '404':
          description: Todo not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TodoNotFound'  
        '401':
          description: The username provided is not part of the boolean-uk github organisation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GithubAuthIssue'                        
components:
  schemas:
    Todo:
      required:
        - title
      type: object
      properties:
        id:
          type: number
          example: 10
        title:
          type: string
          example: Clean my room
        completed:
          type: boolean
          description: whether the todo has been completed
    TodoNotFound:
      type: object
      properties:
        error:
          type: string
          example: todo not found
    BadRequest:
      type: object
      properties:
        error:
          type: array
          example: 
            - body - title is required
            - params - id must be a number
          items:
            type: string
    GithubAuthIssue:
      type: object
      properties:
        error:
          type: string
          example: you must be part of the boolean-uk organisation to use this api
  requestBodies:
    Todo:
      description: Todo object that needs to be added to the list
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Todo'
